version: '3'

services:
  db:
    image: postgres
    container_name: kanastra-db

    ##### Retirei o bind mount porque não funcionava no actions
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/

    environment:
      POSTGRES_DB: kanastra_db
      POSTGRES_USER: kanastra_user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_PORT: 5432

    ports:
      - "5432:5432" # Map port 5432 on the host to port 5432 in the container

  web:
    image: back
    container_name: back
    build: ./backend

    ##### Retirei o bind mount porque não funcionava no actions
    # volumes:
    #   - ./backend/kanastra:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: kanastra_db
      DB_USER: kanastra_user
      DB_PASSWORD: mypassword
      DB_HOST: db
      DB_PORT: 5432

  frontend:
    image: front
    container_name: front
    build: ./frontend
    volumes:
      - ./frontend/front:/app
    ports:
      - "3000:3000"

volumes:
  postgres_data:
